/// <reference types="vite/client" />
/// <reference types="vite-plugin-svgr/client" />

export { default as ProfileIcon } from './icon/profile-icon.svg?react'
export { default as CalendarIcon } from './icon/calendar-icon.svg?react'
export { default as DropdownIcon } from './icon/dropdown-icon.svg?react'
export { default as UserIcon } from './icon/user-icon.svg?react'
export { default as BookIcon } from './icon/book-icon.svg?react'
export { default as AngleUpIcon } from './icon/angle-up.svg?react'
export { default as AngleDownIcon } from './icon/angle-down.svg?react'
export { default as XbuttonIcon } from './icon/x-icon.svg?react'
export { default as ArrowLeftIcon } from './icon/sg-arrow-left-icon.svg?react'
export { default as ArrowRightIcon } from './icon/sg-arrow-right-icon.svg?react'
export { default as DoubleArrowLeftIcon } from './icon/db-arrow-left-icon.svg?react'
export { default as DoubleArrowRightIcon } from './icon/db-arrow-right-icon.svg?react'
export { default as ToastCheckIcon } from './icon/toast-check-icon.svg?react'
export { default as WarningIcon } from './icon/warning-icon.svg?react'
export { default as SuccessIcon } from './icon/success-icon.svg?react'
export { default as ErrorIcon } from './icon/error-icon.svg?react'
export { default as SuccessCloseIcon } from './icon/success-close-icon.svg?react'
export { default as FailCloseIcon } from './icon/fail-close-icon.svg?react'
export { default as SelectedCheckIcon } from './icon/selected-check-icon.svg?react'
export { default as CheckIcon } from './icon/check-icon.svg?react'
export { default as LogoUpload } from './images/logo-upload.svg?react'
export { default as PencilIcon } from './icon/pencil-icon.svg?react'
export { default as OpeningAngleIcon } from './icon/opening-angle-bracket.svg?react'
export { default as ClosingAngleIcon } from './icon/closing-angle-bracket.svg?react'
export { default as OzcodingLogo } from './images/ozcoding-logo.svg'
export { default as CancelIcon } from './icon/cancel-icon.svg?react'
export { default as AnswerIcon } from './icon/answer-check-icon.svg?react'
